#!/command/with-contenv sh

if curl --insecure --fail --silent --show-error --max-time 5 \
        "http://127.0.0.1:8000/alive" >/dev/null 2>&1; then
    echo "✅ Vaultwarden RUN."
    exit 0
else
    echo "❎ Vaultwarden STOP."
    exit 1
fi
