FROM --platform=$TARGETPLATFORM ghcr.io/pfm-powerforme/vaultwarden:main-alpine

RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone

RUN apk --no-cache add \
        tar \
        s3cmd

RUN echo '* * * * * root sh -c "/backup.sh"' >> /etc/crontab

COPY docker/backup.sh /backup.sh
COPY docker/start-alpine.sh /start-alpine.sh

RUN chmod +x /backup.sh && chmod +x /start-alpine.sh

CMD ["/start-alpine.sh"]