name: PFM-Container-build

on:
  workflow_dispatch:  # click the button on Github repo!
  workflow_call:

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  docker-build:
    name: 'Build Vaultwarden containers'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: linux/arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    outputs:
      image_name: ${{ steps.work_env.outputs.image_name }}
      platform_pair: ${{ steps.work_env.outputs.platform_pair }}
      arch: ${{ steps.work_env.outputs.arch }}
    env:
      SOURCE_COMMIT: ${{ github.sha }}
      SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"

    steps:
      - name: '环境变量'
        id: work_env
        run: |
          repo=${{ github.event.repository.name }}
          platform=${{ matrix.platform }}
          echo "image_name=${repo,,}" >> ${GITHUB_OUTPUT}
          echo "IMAGE_NAME=${repo,,}" >> ${GITHUB_ENV}
          echo "platform_pair=${platform//\//-}" >> ${GITHUB_OUTPUT}
          echo "PLATFORM_PAIR=${platform//\//-}" >> ${GITHUB_ENV}
          echo "arch=${platform#*/}" >> ${GITHUB_OUTPUT}
          echo "ARCH=${platform#*/}" >> ${GITHUB_ENV}
          echo "GH=${{ vars.GHCR_REPO }}/${repo,,}" >> ${GITHUB_ENV}

      - name: '检出分支'
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: '设置容器编译工具'
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          cache-binary: true
          cleanup: true
          platforms: ${{ matrix.platform }}
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2
          driver-opts: |
            network=host

      - name: 'Determine Base Tags and Source Version'
        shell: bash
        env:
          REF_TYPE: ${{ github.ref_type }}
        run: |
          if [[ "${REF_TYPE}" == "tag" ]]; then
            echo "BASE_TAGS=latest,${GITHUB_REF#refs/*/}" | tee -a "${GITHUB_ENV}"
          elif [[ "${REF_TYPE}" == "branch" ]]; then
            echo "BASE_TAGS=main" | tee -a "${GITHUB_ENV}"
          fi
          echo "SOURCE_VERSION=${SOURCE_COMMIT}-$(date +'%Y-%m-%d')" | tee -a "${GITHUB_ENV}"

      - name: '登录GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Add registry for ghcr.io'
        shell: bash
        env:
          GHCR_REPO: ${{ env.GH }}
        run: |
          echo "CONTAINER_REGISTRIES=${CONTAINER_REGISTRIES:+${CONTAINER_REGISTRIES},}${GHCR_REPO}" | tee -a "${GITHUB_ENV}"

      - name: 'Configure build cache from/to'
        shell: bash
        env:
          GHCR_REPO: ${{ env.GH }}
          BASE_IMAGE: alpine
        run: |
            echo "BAKE_CACHE_FROM=type=registry,ref=${GHCR_REPO}-buildcache:${BASE_IMAGE}" | tee -a "${GITHUB_ENV}"
            echo "BAKE_CACHE_TO=type=registry,ref=${GHCR_REPO}-buildcache:${BASE_IMAGE},compression=zstd,mode=max" | tee -a "${GITHUB_ENV}"


      - name: '编译并发布'
        id: bake
        uses: docker/bake-action@v6
        env:
          BASE_TAGS: "${{ env.BASE_TAGS }}"
          SOURCE_COMMIT: "${{ env.SOURCE_COMMIT }}"
          SOURCE_VERSION: "${{ env.SOURCE_VERSION }}"
          SOURCE_REPOSITORY_URL: "${{ env.SOURCE_REPOSITORY_URL }}"
          CONTAINER_REGISTRIES: "${{ env.CONTAINER_REGISTRIES }}"
        with:
          source: .
          files: docker/docker-bake.hcl
          targets: "alpine-${{ env.ARCH }}"
          set: |
            *.cache-from=${{ env.BAKE_CACHE_FROM }}
            *.cache-to=${{ env.BAKE_CACHE_TO }}
            *.output=type=image,name=${{ env.GH }},push-by-digest=true,name-canonical=true,push=true

      - name: '导出 digest'
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ fromJSON(steps.bake.outputs.metadata).image['containerimage.digest'] }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: '上传 artifact'
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: '容器合并'
    needs: docker-build
    runs-on: ubuntu-latest
    env:
      GH: ${{ vars.GHCR_REPO }}/${{ needs.docker-build.outputs.image_name }}
    steps:
      - name: '下载 digests'
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: '设置容器编译工具'
        uses: docker/setup-buildx-action@v3

      - name: '登录GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: '创建并发布多架构 manifest'
        working-directory: ${{ runner.temp }}/digests
        run: |
          ls .
          docker buildx imagetools create \
            -t ${{ env.GH }}:latest-alpine \
           $(printf '${{ env.GH }}@sha256:%s ' *)
           
      - name: '检查容器'
        run: |
          docker buildx imagetools inspect ${{ env.GH }}:latest-alpine

  Call-next-workflow:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    needs: merge
    uses: ./.github/workflows/custom-container-build.yml
    secrets: inherit
