name: 'Deploy-to-Koyeb'
on:
  workflow_dispatch:
  workflow_call:

permissions: write-all

jobs:
  Deploy:
    name: 'Koyeb 部署'
    runs-on: ubuntu-latest
    steps:
      - name: '安装 Koyeb CLI'
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
      - name: '部署到 Koyeb'
        run: koyeb service redeploy my-services/vaultwarden